"""Seed expert profiles — 10 experts from publicly available information.

These profiles are derived from publicly available Google Scholar profiles,
institutional pages, and published papers. Used for MVP demonstration.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from askpeer.models import Expert

EXPERTS: list[Expert] = [
    Expert(
        id="exp_001",
        name="Prof. Nieng Yan",
        affiliation="Shenzhen Medical Academy / Tsinghua University",
        domains=["structural biology", "membrane proteins", "cryo-EM"],
        methods=["single-particle cryo-EM", "X-ray crystallography", "biochemistry"],
        techniques=["grid preparation", "data processing", "model building", "GLUT transporters"],
        bio="World-leading structural biologist specializing in membrane transport proteins. Solved structures of glucose transporters and ion channels using cryo-EM.",
        h_index=80,
        google_scholar="https://scholar.google.com/citations?user=nieng_yan",
        profile_text="Prof. Nieng Yan is a structural biologist specializing in membrane protein structure determination using single-particle cryo-EM and X-ray crystallography. Her lab has solved structures of human glucose transporters (GLUT1-4), voltage-gated sodium channels, and other physiologically critical membrane proteins. Expert in difficult membrane protein sample preparation, grid optimization, and high-resolution data processing using cryoSPARC and RELION.",
    ),
    Expert(
        id="exp_002",
        name="Prof. David Baker",
        affiliation="University of Washington / Institute for Protein Design",
        domains=["protein design", "computational biology", "structural biology"],
        methods=["Rosetta", "deep learning", "protein structure prediction"],
        techniques=["Rosetta software", "protein folding", "de novo design", "RFdiffusion"],
        bio="Nobel laureate. Pioneer of computational protein design. Creator of Rosetta and RosettaFold. Designs novel proteins from scratch.",
        h_index=150,
        google_scholar="https://scholar.google.com/citations?user=david_baker",
        profile_text="Prof. David Baker leads the Institute for Protein Design at UW. His group developed Rosetta, RosettaFold, and RFdiffusion for computational protein design and structure prediction. Expertise spans de novo protein design, protein folding principles, deep learning for biomolecular modeling, and designing functional proteins including enzymes, binders, and self-assembling materials.",
    ),
    Expert(
        id="exp_003",
        name="Prof. Ron Dror",
        affiliation="Stanford University",
        domains=["molecular dynamics", "computational biology", "GPCRs"],
        methods=["molecular dynamics simulation", "machine learning", "Markov state models"],
        techniques=["Anton supercomputer", "DESMOND", "long-timescale MD", "force field development"],
        bio="Leader in long-timescale molecular dynamics simulations. Uses Anton supercomputer to simulate millisecond-scale protein dynamics.",
        h_index=70,
        google_scholar="https://scholar.google.com/citations?user=ron_dror",
        profile_text="Prof. Ron Dror's lab at Stanford specializes in long-timescale molecular dynamics simulations of biomolecular systems, particularly GPCRs and membrane proteins. Using the Anton supercomputer, they achieve millisecond-scale simulations to study protein activation mechanisms, drug binding pathways, and allosteric regulation. Expert in MD force field parameterization, Markov state model analysis, and ML-enhanced simulation analysis.",
    ),
    Expert(
        id="exp_004",
        name="Prof. Andrey Rogach",
        affiliation="City University of Hong Kong",
        domains=["carbon dots", "nanomaterials", "photoluminescence"],
        methods=["colloidal synthesis", "optical spectroscopy", "nanomaterial characterization"],
        techniques=["hydrothermal synthesis", "TEM", "time-resolved PL", "quantum yield measurement"],
        bio="Leading researcher in carbon dots and luminescent nanomaterials. Extensive work on synthesis-structure-property relationships.",
        h_index=120,
        google_scholar="https://scholar.google.com/citations?user=andrey_rogach",
        profile_text="Prof. Andrey Rogach is a leading expert in colloidal nanomaterials, particularly carbon dots and semiconductor quantum dots. His group focuses on synthesis methods (hydrothermal, microwave, solvothermal), surface functionalization, and photoluminescence mechanisms of carbon dots. Deep expertise in optical characterization, quantum yield optimization, and applications in sensing, bioimaging, and optoelectronics.",
    ),
    Expert(
        id="exp_005",
        name="Prof. Daphne Koller",
        affiliation="Stanford University / Insitro",
        domains=["machine learning", "computational biology", "drug discovery"],
        methods=["probabilistic graphical models", "deep learning", "causal inference"],
        techniques=["Bayesian networks", "representation learning", "ML for biology"],
        bio="Pioneer in applying probabilistic ML to biology. Co-founder of Coursera. CEO of Insitro — ML-driven drug discovery.",
        h_index=130,
        google_scholar="https://scholar.google.com/citations?user=daphne_koller",
        profile_text="Prof. Daphne Koller bridges machine learning and biomedicine. Her work spans probabilistic graphical models, causal inference, and deep learning applied to genomics, drug discovery, and disease modeling. Through Insitro, she applies ML to generate and analyze large biological datasets for target identification and drug development. Expertise in translating abstract ML methods to real biological problems.",
    ),
    Expert(
        id="exp_006",
        name="Prof. Cesar de la Fuente",
        affiliation="University of Pennsylvania",
        domains=["antimicrobial peptides", "AI for drug discovery", "synthetic biology"],
        methods=["deep learning", "peptide design", "high-throughput screening"],
        techniques=["AMP discovery", "molecular dynamics", "sequence-activity modeling"],
        bio="Pioneer in using AI to discover antimicrobial peptides. Mines extinct organisms' proteomes for therapeutic molecules.",
        h_index=55,
        google_scholar="https://scholar.google.com/citations?user=cesar_fuente",
        profile_text="Prof. Cesar de la Fuente uses AI and computational methods to discover novel antimicrobial peptides (AMPs). His lab applies deep learning to mine proteomes — including from extinct organisms — for therapeutic peptides. Expertise in peptide sequence-activity relationship modeling, molecular dynamics validation, and high-throughput in vitro screening. Combines evolutionary biology with ML for antibiotic discovery.",
    ),
    Expert(
        id="exp_007",
        name="Prof. Frank Noe",
        affiliation="Freie Universität Berlin / Microsoft Research",
        domains=["computational chemistry", "molecular dynamics", "machine learning"],
        methods=["Markov state models", "deep learning", "enhanced sampling"],
        techniques=["PyEMMA", "Boltzmann generators", "VAMPnets", "coarse-graining"],
        bio="Leader in combining ML with molecular simulations. Developed VAMPnets and Boltzmann generators for enhanced sampling.",
        h_index=75,
        google_scholar="https://scholar.google.com/citations?user=frank_noe",
        profile_text="Prof. Frank Noe develops machine learning methods for molecular simulations. His group created Markov state models, VAMPnets, and Boltzmann generators — methods that use deep learning to analyze and accelerate molecular dynamics. Expertise in enhanced sampling, coarse-graining, and ML force fields. Bridges statistical mechanics with modern ML at Microsoft Research.",
    ),
    Expert(
        id="exp_008",
        name="Prof. Aviv Regev",
        affiliation="Genentech / Broad Institute",
        domains=["single-cell genomics", "computational biology", "bioinformatics"],
        methods=["single-cell RNA-seq", "spatial transcriptomics", "deep learning"],
        techniques=["scRNA-seq analysis", "gene regulatory networks", "cell atlas construction"],
        bio="Pioneer of single-cell genomics. Led the Human Cell Atlas. Head of Research at Genentech.",
        h_index=140,
        google_scholar="https://scholar.google.com/citations?user=aviv_regev",
        profile_text="Prof. Aviv Regev is a pioneer in single-cell genomics and computational biology. Her work on single-cell RNA-seq analysis methods transformed how we study cellular heterogeneity. Led the Human Cell Atlas consortium. Expertise in gene regulatory network inference, spatial transcriptomics, and applying deep learning to large-scale genomic data for therapeutic discovery.",
    ),
    Expert(
        id="exp_009",
        name="Prof. Andrew Gelman",
        affiliation="Columbia University",
        domains=["statistics", "Bayesian inference", "causal inference"],
        methods=["Bayesian hierarchical modeling", "MCMC", "model checking"],
        techniques=["Stan", "R", "posterior predictive checking", "multilevel modeling"],
        bio="Foremost Bayesian statistician. Author of BDA3. Creator of Stan probabilistic programming language.",
        h_index=110,
        google_scholar="https://scholar.google.com/citations?user=andrew_gelman",
        profile_text="Prof. Andrew Gelman is a leading Bayesian statistician. His work covers hierarchical modeling, causal inference, MCMC methods, and statistical graphics. Co-created the Stan probabilistic programming language. Expert in helping researchers design statistically sound experiments — from sample size calculations to complex multilevel models for biological and social data.",
    ),
    Expert(
        id="exp_010",
        name="Prof. Jennifer Doudna",
        affiliation="UC Berkeley / Innovative Genomics Institute",
        domains=["CRISPR", "gene editing", "structural biology"],
        methods=["cryo-EM", "biochemistry", "genome engineering"],
        techniques=["CRISPR-Cas9", "RNA biology", "in vitro transcription"],
        bio="Nobel laureate. Co-inventor of CRISPR-Cas9 gene editing. Structural and mechanistic studies of CRISPR systems.",
        h_index=130,
        google_scholar="https://scholar.google.com/citations?user=jennifer_doudna",
        profile_text="Prof. Jennifer Doudna is a Nobel laureate who co-invented CRISPR-Cas9 genome editing. Her lab uses structural biology (cryo-EM, X-ray crystallography) and biochemistry to understand CRISPR mechanisms and develop new genome engineering tools. Expertise in RNA biology, Cas protein characterization, and translating basic CRISPR research into therapeutic applications.",
    ),
]
